Select * From products;

-- Q1 What is the total revenue generated by male vs female customers  
Select gender,Sum(purchase_amount) As total_revenue From products Group by gender;

-- Q2 Which customers get the discount but still spend more than the average purchase amount?
Select customer_id, purchase_amount From products Where discount_applied = "Yes"
and purchase_amount > (Select Avg(purchase_amount) From products);

-- Q3 Which are the top 5 products with highest average review rating
Select item_purchased,Round(Avg(review_rating),1) as average_review_rating From products
Group by item_purchased Order by average_review_rating desc limit 5;

-- Q4 Compare the average purchase amount of Standard and Express shipping 
Select shipping_type,Round(Avg(purchase_amount),1) As average_purchase_amount
From products Where shipping_type="Express" or shipping_type="Standard"
Group by shipping_type;

-- Q5 Do the subscribed customers spend more? compare the average spending and total revenue between the susbcribed and non-susbcribed customers
Select subscription_status,Round(Avg(purchase_amount),1)
As average_purchase_amount,Sum(purchase_amount) As total_revenue
From products Group by subscription_status;

-- Q6 Find top 5 products with highest percentage of purchase and discount applied
Select item_purchased,Round(((Sum(purchase_amount)/(Select Sum(purchase_amount)
From products WHERE discount_applied = 'Yes'))*100),1) As higest_purchased_percentage
From products Where discount_applied="Yes" Group by item_purchased
Order by higest_purchased_percentage desc limit 5;

-- Q7 Segment the customers into new,returning,loyal based on their previous purchases
-- and show the count of each segment
Select previous_purchases,Case When previous_purchases=1 Then "New" When previous_purchases Between 2 And 10 Then "Returning" Else "Loyal"
End As customer_segment From products;

Select previous_purchases,if(previous_purchases=1,"New",if(previous_purchases Between 2 And 10,"Returning","Loyal")) As customer_segment From products; 

-- Q8  What are the top 3 most purchased products within each category
-- That entire aprt means the With (and the window functions written in it are used only in the CTE(Common Table Expression) in SQL
-- we cannot use the window functions because of the processing process of the SQL)
With main As(
Select item_purchased,category,Count(item_purchased) As total_orders, 
Row_Number() Over(Partition By category Order By Count(item_purchased) desc) As rank_number
From products Group By item_purchased,category
)
Select item_purchased,category,total_orders From main Where rank_number<=3;

-- Q9 Are customers who are repeat buyers(more than 5 previuous purchases) also likely to subscribe?
Select subscription_status,Count(customer_id) as repeat_customers From products Where previous_purchases>5 Group by subscription_status;

-- Q10 What is the revenue contribution of each age group
Select age_group,Sum(purchase_amount) As total_revenue From products Group by age_group;